apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-order-service
  namespace: reddog
  labels:
    app: retail-order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-order-service
  template:
    metadata:
      labels:
        app: retail-order-service
      annotations:
        dapr.io/enabled: 'true'
        dapr.io/app-id: retail-order-service
        dapr.io/app-port: '80'
    spec:
      containers:
        - name: retail-order-service
          image: seanacr.azurecr.io/azure/reddog-retail-demo/reddog-retail-order-service:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /probes/ready
              port: 80
            timeoutSeconds: 30
            successThreshold: 1
            failureThreshold: 12
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /probes/healthz
              port: 80
            failureThreshold: 6
            periodSeconds: 10